    a=int(input("enter the value of a:"))
    b=int(input("enter the value of b:"))
    print("THE SUM IS:",a+b)
    print("THE DIFFERENCE IS:",a-b)
    print("THE PRODUCT IS:",a*b)
    print("THE QUOTIENT IS:",a/b)
